services:
  tor-proxy:
    image: dperson/torproxy
    container_name: tor-proxy
    restart: unless-stopped
    ports:
      - "9050:9050" 
      - "8118:8118"
    environment:
      - TZ=America/Sao_Paulo
